config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
	default_url_options host: ENV['HOST_URL']

	devise_for :users, controllers: {sessions: 'users/sessions',
	                                 registrations: 'users/registrations'}

	mount LetterOpenerWeb::Engine, at: '/letter_opener', as: 'letter_opener' if Rails.env.development?

	authenticate :user, -> (user) { user.has_role? User::ROLE_ADMIN } do
		mount RailsAdmin::Engine, at: '/admin', as: 'rails_admin'
		mount Sidekiq::Web, at: '/sidekiq', as: 'sidekiq'
	end

	authenticate :user do
		if Rails.env.production?
			SequenceServer.init
			mount SequenceServer, at: ENV['SEQUENCESERVER_MOUNT_PATH'], as: 'sequenceserver'
			get "#{ENV['SEQUENCESERVER_MOUNT_PATH']}/get_sequence/", to: 'sequence_server#get_sequence'
			get "#{ENV['SEQUENCESERVER_MOUNT_PATH']}/download/", to: 'sequence_server#download'
		end
	end

	root to: 'home#index'

	resources :contacts, only: %i[create]
	resources :data, only: %i[index show create] do
		collection do
			get :refresh
		end
	end
	resources :home, only: %i[index]
	resources :media, only: %i[index show]
	resources :publications, only: %i[index]
end

app/views/globals/_flashes.html.erb
<script>
	<% flash.each do |key, message| %>
	toastr["<%= flash_error_class key %>"]("<%= message %>");
	<% end %>
</script>

app/views/globals/_footer.html.erb
<footer class="footer">
    <div class="footer_body">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 footer_col">
                    <div class="newsletter_container d-flex flex-column align-items-start justify-content-end">
                        <div class="footer_logo mb-auto"><a href="#">Nanyang Technological University</a></div>
                    </div>
                </div>

                <!-- About -->
                <div class="col-lg-2 offset-lg-3 footer_col">
                    <div>
                        <div class="footer_title">About Us</div>
                        <ul class="footer_list">
                            <li><a href="#">Courses</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">NTU Guidelines</a></li>
                            <li><a href="#">Jobs</a></li>
                            <li><a href="#">Advertise with us</a></li>
                            <li><a href="#">Press</a></li>
                            <li><a href="#">Contact us</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="copyright_content d-flex flex-md-row flex-column align-items-md-center align-items-start justify-content-start">
                        <div class="cr">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                            All rights reserved
                            |
                            This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by
                            <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </div>

                        <div class="cr_right ml-md-auto">
                            <div class="footer_phone"><span class="cr_title">phone:</span>+00</div>
                            <div class="footer_social">
                                <span class="cr_social_title">follow us</span>
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/globals/_footer_small.html.erb
<footer class="footer">
	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="copyright_content d-flex flex-md-row flex-column align-items-md-center align-items-start justify-content-start">
						<div class="cr">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							Copyright &copy;<script>document.write(new Date().getFullYear());</script>
							All rights reserved
							|
							This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by
							<a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</div>

						<div class="cr_right ml-md-auto">
							<div class="footer_phone"><span class="cr_title">phone:</span>+65 6790 9845</div>
							<div class="footer_social">
								<span class="cr_social_title">follow us</span>
								<ul>
									<% SocialMedium.order(:position).each do |social_medium| %>
										<li>
											<a href="<%= social_medium.url %>" target="_blank">
												<%= social_medium.display_icon %>
											</a>
										</li>
									<% end %>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>

app/views/globals/_header.html.erb
<header class="header">
	<!-- Top Bar -->
	<div class="top_bar">
		<div class="top_bar_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="top_bar_content d-flex flex-row align-items-center justify-content-start">
							<div class="logo_container mr-auto">
							</div>

							<nav class="main_nav_contaner">
								<ul class="main_nav">
									<li class="active"><%= link_to 'Home', home_index_path %></li>
									<li><%= link_to 'Publications', publications_path %></li>
									<li><%= link_to 'Media', media_path %></li>

									<li><%= link_to 'Data', data_path if can? :read, :datum %></li>
									<li><%= link_to 'Search', ENV['SEQUENCESERVER_MOUNT_PATH'] if can? :search, :sequenceserver %></li>
								</ul>
							</nav>

							<div class="header_content_right ml-auto text-right">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Header Content -->
	<div class="header_container">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="logo_container mr-auto">
							<%= link_to home_index_path do %>
								<div class="logo_text">
									<%= ENV['WEBSITE_NAME'] %>
									<small><%= "(#{ENV['WEBSITE_SUBTITLE']})" if ENV['WEBSITE_SUBTITLE'].present? %></small>
								</div>
							<% end %>
						</div>

						<div class="header_content_right ml-auto text-right">
							<% unless devise_controller? %>
								<% if user_signed_in? %>
									<div class="user dropdown">
										<%= link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'}, aria: {haspopup: true, expanded: false} do %>
											<i class="fa fa-user"></i>
										<% end %>
										<ul class="dropdown-menu">
											<% if can? :access, :rails_admin %>
												<li class="dropdown-item">
													<%= link_to rails_admin.dashboard_path do %>
														<i class="fa fa-cogs"></i>&nbsp;Admin Panel
													<% end %>
												</li>
											<% end %>
											<li class="dropdown-item">
												<%= link_to destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure you want to Sign Out?'} do %>
													<i class="fa fa-sign-out"></i>&nbsp;Sign Out
												<% end %>
											</li>
										</ul>
									</div>
								<% else %>
									<nav class="main_nav_contaner">
										<ul class="main_nav">
											<li><%= link_to 'Login/Register', '#', class: 'btn', data: {toggle: 'modal', target: '#user-authenticate-modal'} %></li>
										</ul>
									</nav>
								<% end %>
							<% end %>

							<!-- Hamburger -->
							<div class="hamburger menu_mm">
								<i class="fa fa-bars menu_mm" aria-hidden="true"></i>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>

<!-- Mobile Menu -->
<div class="menu d-flex flex-column align-items-end justify-content-start text-right menu_mm trans_400">
	<div class="menu_close_container">
		<div class="menu_close">
			<div></div>
			<div></div>
		</div>
	</div>

	<nav class="menu_nav">
		<ul class="menu_mm">
			<li class="menu_mm"><%= link_to 'Home', home_index_path %></li>
			<li class="menu_mm"><%= link_to 'Publications', publications_path %></li>
			<li class="menu_mm"><%= link_to 'Media', media_path %></li>
			<li class="menu_mm"><%= link_to 'Data', data_path if can? :read, :datum %></li>
			<li class="menu_mm"><%= link_to 'Search', ENV['SEQUENCESERVER_MOUNT_PATH'] if can? :search, :sequenceserver %></li>
		</ul>
	</nav>

	<div class="menu_extra">
		<nav class="menu_nav">
			<ul class="menu_mm">
				<% if user_signed_in? %>
					<% if can? :access, :rails_admin %>
						<li class="menu_mm"><%= link_to 'Admin Panel', rails_admin.dashboard_path %></li>
					<% end %>
					<li class="menu_mm">
						<%= link_to 'Sign Out', destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure you want to Sign Out?'} %>
					</li>
				<% else %>
					<li class="menu_mm">
						<%= link_to 'Login/Register', '#', data: {toggle: 'modal', target: '#user-authenticate-modal'} %>
					</li>
				<% end %>
			</ul>
		</nav>
	</div>
</div>